# Theme
remote_theme: epidrome/cover-card@main

# Title and tag line
title: 'Juan Almeida'
description: 'Você pode encontrar meus contatos e projetos logo abaixo'

# Images
avatar: 'https://avatars.githubusercontent.com/u/15617091?v=4'
background: 'https://wallpapershome.com/images/pages/pic_h/5708.jpg'
favicon: 'favicon.ico'

# Online profiles
bluesky: 'juanvic.bsky.social'
linkedin: 'juanvic-almeida'
instagram: 'juanvic04'
github-user: 'Juanvic'
blog_url: 'https://juanvic.github.io/'
email: 'juanvic.almeida@gmail.com'
mastodon: '@juanvic'

social-links-order: [github-user, bluesky, mastodon, instagram, linkedin, blog_url, email]

social-links:
  - name: bluesky
    url-pattern: bsky.app/profile/__USERNAME__
    icon-class: fab fa-2x fa-bluesky

  - name: linkedin
    url-pattern: linkedin.com/in/__USERNAME__

  - name: instagram
    url-pattern: instagram.com/__USERNAME__

  - name: github-user
    url-pattern: github.com/__USERNAME__
    icon-class: fab fa-2x fa-github

  - name: mastodon
    url-pattern: mastodon.social/__USERNAME__
    icon-class: fab fa-2x fa-mastodon

  - name: blog_url
    url-pattern: '__USERNAME__'
    icon-class: fas fa-2x fa-blog

  - name: email
    url-scheme: 'mailto:'
    url-pattern: '__USERNAME__'
    icon-class: far fa-2x fa-envelope-open
